# Generated by Django 5.1.1 on 2024-09-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shippingCharge',
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_method',
            field=models.CharField(choices=[('courier', 'Доставка курьером'), ('pickup', 'Самовывоз')], default='courier', max_length=20, verbose_name='Способ доставки'),
        ),
    ]
