# Generated by Django 5.1.1 on 2024-09-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_shippingcharge_cart_delivery_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='banners_shop/', verbose_name='Изображение баннера')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения баннеров', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Баннер магазина',
                'verbose_name_plural': 'Баннеры магазина',
                'ordering': ['order'],
            },
        ),
    ]
