# Generated by Django 5.1.1 on 2024-09-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_bannershop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Введите имя', max_length=100, verbose_name='Полное имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные курьеру'), ('card', 'Карта')], max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
