# Generated by Django 5.1.1 on 2024-09-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_order_city_alter_order_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('button_text', models.CharField(default='Подробнее', max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки')),
            ],
            options={
                'verbose_name': 'Элемент продукции',
                'verbose_name_plural': 'Элементы продукции',
            },
        ),
    ]
